### ISSUE TITLE
ip shananigans

### ISSUE THREAD

**Issue by Terminus18** [Terminus18/AberothClient#2]
At this time, the login form for username and password appears to be working, the issue is the IP. I cannot find a way to have the ip automatically appear in aberoth.min.js if its inputed via an HTML form.

If I can get the to work, then the client should work for all logins. If you want to see the error, use browser console at https://terminus18.github.io/AberothClient/ while trying to login.

**Comment by thewebventure** [comment]
you can do this by calling global object window.autoLoad.
So, if you do this :
`var userIpAddress =  window.autoLoad.ipaddress`
the value `userIpAddress` will have the value of the users IP address.

do what you need to do with user IP :)

- Ordinax

**Comment by thewebventure** [comment]
I just figured that by using a third party script, you can do this...
so i will update it
